#' Compute cell-cell interaction network.
#'
#' Analyze the mean expression data generated by the computeValue method of
#' CellRouter to determine co-expression patterns of ligands and receptors.
#'
#' @param mean.expr list; the statistics of the expressed genes as calculated by
#' the computeValue method of CellRouter.
#' @param ligands vector; list of genes annotated as ligands.
#' @param receptors vector; list of genes annotated as receptors.
#' @param threshold numeric; threshold to select the genes in the population
#' according to their mean expression.
#' @param pairs the pairs;
#'
#' @return data frame; interactions with celltype1, celltype2, pair, ligand,
#' and receptor.
#'
#' @export
pathfinding <- function(cellrouter, assay.type='ST', grn, gene.pairs, markers, maindir=NULL, verbose=TRUE){
  tfs <- intersect(grn.data$tfs, rownames(slot(object, 'assays')[[assay.type]]@ndata))

  sts2 <- list()
  for(i in unique(gene.pairs$celltypes)){
    gene.pairs.celltypes <- gene.pairs[which(gene.pairs$celltypes == i),]
    rs <- unique(gene.pairs.celltypes$receptor)
    sts2[["receptor"]][[i]]$sources <- rs  # receptors
    sts2[["receptor"]][[i]]$targets <- tfs # TFs (all)
  }
  if (maindir == NULL) {
    wd_package <- getwd()
    maindir <- paste0(wd_package, '')
  }
  setwd(maindir)
  
  interactionList <- expand.grid(gene.pairs$celltypes)

  cellcomm <- CreateCellComm()
  for(interaction in interactionList){
    interaction <- gsub(" ", ".", interaction)
    print(interaction)
    celltype <- strsplit(interaction, split = "[_]")[[1]][2]
  
    cat("Using ", celltype, " coexpression network\n")
    filename <- paste(celltype, ".txt", sep='')
    dirname <- gsub(("[.]"), ".", interaction)
    cellcomm <- findpaths.simpleRJava(cellcomm, sources.targets = sts2$receptor[[interaction]], file = filename, dir = dirname, maindir = maindir)
  }

  files <- list()
  for(i in interactionList){
    f <- paste(strsplit(i, split = "_")[[1]][2], ".txt", sep = "")
    files[[i]] <- f
  }

  summary <- summarize.flow(files, prefix = "")
  grn_table <- grn$GRN_table
  colnames(grn_table) <- c("target", "reg", "zscore", "corr")
  apathways <- activeSignaling(data = slot(object, 'assays')[[assay.type]]@ndata, sampTab = slot(object, 'assays')[[assay.type]]@sampTab,
                             grn = grn_table, markers = markers, summary = summary, fc = 0.2)
  npaths <- rankpaths(summary, apathways$pathways)
  return(npaths)
}
